### ISSUE TITLE
Type error and infinite spinner

### ISSUE THREAD

**Issue by f0rr0** [infinitered/solidarity#210]
```
TypeError: Cannot read property '1' of null
    at module.exports (/Users/sid/Dev/mobile-app/node_modules/solidarity-react-native/extensions/helpers/getAndroidEnvData.js:13:93)
    at Object.check (/Users/sid/Dev/mobile-app/node_modules/solidarity-react-native/extensions/react-native.js:28:15)
    at Object.<anonymous> (/Users/sid/Dev/mobile-app/node_modules/solidarity/dist/extensions/functions/checkRequirement.js:124:72)
    at Generator.next (<anonymous>)
    at /Users/sid/Dev/mobile-app/node_modules/solidarity/dist/extensions/functions/checkRequirement.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/sid/Dev/mobile-app/node_modules/solidarity/dist/extensions/functions/checkRequirement.js:3:12)
    at map (/Users/sid/Dev/mobile-app/node_modules/solidarity/dist/extensions/functions/checkRequirement.js:62:44)
    at _map (/Users/sid/Dev/mobile-app/node_modules/solidarity/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/Users/sid/Dev/mobile-app/node_modules/solidarity/node_modules/ramda/src/map.js:64:14)
```

**Comment by f0rr0** [comment]
Same issue as https://github.com/infinitered/solidarity/issues/183

**Comment by tabrindle** [comment]
This appears to be coming from regexing the build.gradle file. Can you post that file and it's location?

`projectBuildToolsVersion: /buildToolsVersion\s["|']([\d|.]+)["|']/.exec(androidGradle)[1]`

**Comment by f0rr0** [comment]
`android/app/build.gradle`

```
apply plugin: "com.android.application"
apply plugin: "com.google.firebase.firebase-perf"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

def keystorePropertiesFile = rootProject.file("keystores/release/keystore.properties")
def keystorePlaceholderPropertiesFile = rootProject.file("keystores/debug/keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
	keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
} else {
  keystoreProperties.load(new FileInputStream(keystorePlaceholderPropertiesFile))
}

def VERSION_CODE = 88
def VERSION_NAME = "1.1.1"

// Used when passing in the modified version name in nightly builds
if (project.hasProperty('VERSION_NAME')) {
	VERSION_NAME = project.property('VERSION_NAME')
}

android {

    compileSdkVersion 26

    defaultConfig {
        // FIXME: Enables using multiple versions of google-play-services, at the cost of bundle size.
        // This works around the issue of RN libraries requiring different versions, but if we can
        // find a better way of managing this long-term, that would be better
        multiDexEnabled true

        applicationId "com.dogflight.enroute"
        minSdkVersion 21
        targetSdkVersion 25 // Keep at 25, react-native-notifications package doesn't support 26 and notifications will stop working silently.
        versionCode VERSION_CODE
        versionName VERSION_NAME
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    flavorDimensions "mode"
    productFlavors {
        beta {
            dimension "mode"
        }
        production {
            dimension "mode"
        }
        nightly {
            dimension "mode"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-notifications')
    compile project(':react-native-svg')
    compile project(':react-native-background-timer')
    // ignore unspecified version of play-services-gcm in react-native-device-info
    compile(project(':react-native-device-info')) {
        exclude group: 'com.google.android.gms', module: 'play-services-gcm'
    }
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    // Firebase dependencies
    compile 'com.google.android.gms:play-services-base:15.0.0'
    compile 'com.google.firebase:firebase-core:15.0.0'
    compile 'com.google.firebase:firebase-analytics:15.0.0'
    compile 'com.google.firebase:firebase-crash:15.0.0'
    implementation "com.google.firebase:firebase-perf:15.0.0"
    compile "com.google.android.gms:play-services-gcm:15.0.0"
    compile 'com.google.android.gms:play-services-places:15.0.0'
    compile 'com.google.android.gms:play-services-location:15.0.0'
    compile project(':react-native-google-places')
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.facebook.react:react-native:0.52.0'
    // From node_modules
    // react native maps dependencies
    compile(project(':react-native-maps')) {
      exclude group: 'com.google.android.gms', module: 'play-services-base'
      exclude group: 'com.google.android.gms', module: 'play-services-maps'
    }
    compile 'com.google.android.gms:play-services-maps:15.0.0'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by GantMan** [comment]
@tabrindle - any updates on this?

**Comment by TheAlmightyBob** [comment]
My team is also seeing this issue again. Although there's no stack trace. I don't know if @f0rr0 did something special to get that or if we're actually seeing a slightly different problem.

**Comment by GantMan** [comment]
Bob any chance we can pair tomorrow?

**Comment by TheAlmightyBob** [comment]
@GantMan Perhaps. I'm in the Slack channel (as my name, not my GitHub handle), feel free to ping me.

**Comment by is343** [comment]
I'm still getting this same error as well .
`"solidarity": "2.1.0",
 "solidarity-react-native": "2.0.2",`

**Comment by GantMan** [comment]
Please give a go with solidarity 2.3.0 and solidarity-react-native 2.1.0

**Comment by is343** [comment]
@GantMan 
```
"solidarity": "2.1.0", 
"solidarity-react-native": "2.0.2",
```

There's a new error, but the same result.
It's still infinitely spinning at the 'Verifying Android' step for me.


```
$ /Users/ivan/Desktop/Main_Workspace/paycheck_app_2.0/node_modules/.bin/solidarity
TypeError: Cannot read property 'getAllAndroidSDKs' of undefined
    at module.exports.context (/Users/ivan/Desktop/Main_Workspace/paycheck_app_2.0/node_modules/solidarity-react-native/extensions/helpers/getAndroidEnvData.js:14:31)
    at Object.check (/Users/ivan/Desktop/Main_Workspace/paycheck_app_2.0/node_modules/solidarity-react-native/extensions/react-native.js:28:15)
    at Object.<anonymous> (/Users/ivan/Desktop/Main_Workspace/paycheck_app_2.0/node_modules/solidarity/dist/extensions/functions/checkRequirement.js:125:72)
    at Generator.next (<anonymous>)
    at /Users/ivan/Desktop/Main_Workspace/paycheck_app_2.0/node_modules/solidarity/dist/extensions/functions/checkRequirement.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ivan/Desktop/Main_Workspace/paycheck_app_2.0/node_modules/solidarity/dist/extensions/functions/checkRequirement.js:3:12)
    at map (/Users/ivan/Desktop/Main_Workspace/paycheck_app_2.0/node_modules/solidarity/dist/extensions/functions/checkRequirement.js:62:44)
    at _map (/Users/ivan/Desktop/Main_Workspace/paycheck_app_2.0/node_modules/ramda/src/internal/_map.js:6:19)
    at map (/Users/ivan/Desktop/Main_Workspace/paycheck_app_2.0/node_modules/ramda/src/map.js:64:14)

✔︎ Solidarity checks valid
⠧ Verifying Android
```

**Comment by harrisrobin** [comment]
The first issue I see, is that `envInfo` has been renamed to `envinfo`, so it is undefined: 
https://github.com/infinitered/solidarity/commit/ae02cbfa1c55677348f96e6e874cdbcc17c15df3#diff-d9ddbfcd9acda011201c3a540ff1b402L28

However, even after fixing it locally, it still fails because `envinfo` was updated and they have renamed 
`getAllAndroidSDKs` to `getAndroidSDKInfo` 🙃

Working on a fix, PR coming up shortly.
