### ISSUE TITLE
`gluegun` Dependency Error on Fresh Install

### ISSUE THREAD

**Issue by ElliotChong** [infinitered/solidarity#72]
Greetings,

Just attempted to try `solidarity` for the first time and hit a dependency issue.

Repro steps (on a fresh project):
`yarn add -D solidarity`
`yarn solidarity`

Error is:
```
$ "./node_modules/.bin/solidarity"
module.js:529
    throw err;
    ^

Error: Cannot find module './node_modules/solidarity/bin/../node_modules/gluegun/sniff'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./node_modules/solidarity/bin/solidarity:3:38)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
error Command failed with exit code 1.
```

**Comment by GantMan** [comment]
That's pretty interesting!  Can you verify what version of gluegun got pulled in?

**Comment by GantMan** [comment]
@ElliotChong - fixed!  Thanks so much for the catch.  Be sure to use latest from npm.
